### ISSUE TITLE
PyWeek Entry

### ISSUE THREAD

**Issue by MrTanoshii** [MrTanoshii/PyWeek-33-Metro#12]
- [x] Add all members
- [x] Add Github
- [x] Rename game
- [x] Add game description
- [x] Upload screenshots
- [x] Upload game
- [x] package game into exe

**Comment by BriscoRP** [comment]
Game Name ideas:

- Twin of Destiny
- Twin of Victory
- Twin Expansion
- Twin of Hope
- Goat and Valor
- Goat of Liberty
- Hope and Reckoning
- Evil Voyage
- Evil of Truth
- Twin of Truth

Game Description: 

There is war in the world, history repeating itself. Dictators have too much power and are trying to muscle over democracy. Evil twins around the globe have imprisoned their good brothers and are causing pain and suffering to the innocent. Yin and Yang, good and bad, evil and virtue. Enough is enough, the beloved object Spaghetti Monster has decided that a counter balance is required, to fight evil we need a hero, we need you. Fight your way through each city and rescue the imprisoned brother who can bring peace back to the city. Collect coins, upgrade weapons and improve your abilities as you fight your way across the planet. Use the full guns blazing approach or be quick and evade enemies, it's your fight, it's your strategy. The people need a hero, the people need hope, the people need you.
