### ISSUE TITLE
Audio causing issue

### ISSUE THREAD

**Issue by MrTanoshii** [MrTanoshii/PyWeek-33-Metro#137]
## From PyWeek feedback

I had to remove all sound to be able to run it.
You can only access to the main menu if you are in a level, and go to map and main menu takes you to the map.
The game is fun, I didn't get the theme implementation.

**Comment by mohith01** [comment]
Since we tested for windows and linux i think it's a mac-only problem. This may be a problem which stems from the arcade or pyglet

**Comment by MrTanoshii** [comment]
I've gone through arcade, pymunk and pyglet github issues and it seems all those audio issues were fixed. 

I'm wondering if it's an issue of FFmpeg not being installed
https://pyglet.readthedocs.io/en/latest/programming_guide/media.html

**Comment by MrTanoshii** [comment]
Closed as it cannot be replicated
