### ISSUE TITLE
Other Bugs

### ISSUE THREAD

**Issue by mohith01** [MrTanoshii/PyWeek-33-Metro#35]
Other Bugs Found are:

- [x]  Cannot move cursor while shooting 
- [ ]  Bullets being camouflaged in the Some Maps by the Roads (Probably increase bullet size)

**Comment by MrTanoshii** [comment]
I can't reproduce that bug you mentioned with the cursor being stuck while shooting
When do you get it exactly?

**Comment by MrTanoshii** [comment]
Were you able to reproduce this?

**Comment by mohith01** [comment]
The cursor was a problem with trackpad.. It worked well with the mouse
